// File automatically generated by fshasher

#pragma once

#include <utility>

extern const uint64_t ApotosShamarHashes[];
extern const std::pair<const char *, uint32_t> ApotosShamarFiles[];
extern const size_t ApotosShamarFilesSize;

