// File automatically generated by fshasher

#pragma once

#include <utility>

extern const uint64_t ChunnanHashes[];
extern const std::pair<const char *, uint32_t> ChunnanFiles[];
extern const size_t ChunnanFilesSize;

