// File automatically generated by fshasher

#pragma once

#include <utility>

extern const uint64_t EmpireCityAdabatHashes[];
extern const std::pair<const char *, uint32_t> EmpireCityAdabatFiles[];
extern const size_t EmpireCityAdabatFilesSize;

