// File automatically generated by fshasher

#pragma once

#include <utility>

extern const uint64_t GameHashes[];
extern const std::pair<const char *, uint32_t> GameFiles[];
extern const size_t GameFilesSize;

