// File automatically generated by fshasher

#pragma once

#include <utility>

extern const uint64_t HoloskaHashes[];
extern const std::pair<const char *, uint32_t> HoloskaFiles[];
extern const size_t HoloskaFilesSize;

