// File automatically generated by fshasher

#pragma once

#include <utility>

extern const uint64_t MazuriHashes[];
extern const std::pair<const char *, uint32_t> MazuriFiles[];
extern const size_t MazuriFilesSize;

