// File automatically generated by fshasher

#pragma once

#include <utility>

extern const uint64_t SpagoniaHashes[];
extern const std::pair<const char *, uint32_t> SpagoniaFiles[];
extern const size_t SpagoniaFilesSize;

