// File automatically generated by fshasher

#pragma once

#include <utility>

extern const uint64_t UpdateHashes[];
extern const std::pair<const char *, uint32_t> UpdateFiles[];
extern const size_t UpdateFilesSize;

